// <auto-generated />
using System;
using DzialAudytuBazaDanych;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DzialAudytuBazaDanych.Migrations
{
    [DbContext(typeof(DADbContext))]
    [Migration("20230711081527_first")]
    partial class first
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.8");

            modelBuilder.Entity("DzialAudytuBazaDanych.Tabele.Auction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("CenaPogladowa")
                        .HasColumnType("TEXT");

                    b.Property<string>("Opis")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Auctions");
                });

            modelBuilder.Entity("DzialAudytuBazaDanych.Tabele.Buyer", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("UserId");

                    b.ToTable("Buyers");
                });

            modelBuilder.Entity("DzialAudytuBazaDanych.Tabele.Class", b =>
                {
                    b.Property<string>("Klasa")
                        .HasMaxLength(2)
                        .HasColumnType("TEXT");

                    b.Property<string>("Opis")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<int?>("Rabat")
                        .HasColumnType("INTEGER");

                    b.HasKey("Klasa");

                    b.ToTable("Classes");
                });

            modelBuilder.Entity("DzialAudytuBazaDanych.Tabele.Computer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Aukcja")
                        .HasColumnType("INTEGER");

                    b.Property<string>("CPU")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataAudytu")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataWprowadzenia")
                        .HasColumnType("TEXT");

                    b.Property<string>("Dysk")
                        .HasColumnType("TEXT");

                    b.Property<string>("KartaGraficzna")
                        .HasColumnType("TEXT");

                    b.Property<string>("Klasa")
                        .HasColumnType("TEXT");

                    b.Property<string>("Producent")
                        .HasColumnType("TEXT");

                    b.Property<int?>("RAM")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Computers");
                });

            modelBuilder.Entity("DzialAudytuBazaDanych.Tabele.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
